name: test_2

on:
  push:
    branches:
      - test_2

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Print messages for test_2
        run: |
          echo "Rama 2 – Print 1"
          echo "Rama 2 – Print 2"
          echo "Rama 2 – Print 3"
